#pragma once

#include <cstdint>

namespace ProtoRock {
namespace Protocol {
namespace Packet {

enum struct PacketID : uint32_t {
    Login = 1,
    PlayStatus,
    ServerToClientHandshake,
    ClientToServerHandshake,
    Disconnect,
    ResourcePacksInfo,
    ResourcePackStack,
    ResourcePackClientResponse,
    Text,
    SetTime,
    StartGame,
    AddPlayer,
    AddActor,
    RemoveActor,
    AddItemActor,

    // Skip 1

    TakeItemActor = AddItemActor + 2,
    MoveActorAbsolute,
    MovePlayer,
    PassengerJump,
    UpdateBlock,
    AddPainting,
    TickSync,

    // Skip 1

    LevelEvent = TickSync + 2,
    BlockEvent,
    ActorEvent,
    MobEffect,
    UpdateAttributes,
    InventoryTransaction,
    MobEquipment,
    MobArmourEquipment,
    Interact,
    BlockPickRequest,
    ActorPickRequest,
    PlayerAction,

    // Skip 1

    HurtArmour = PlayerAction + 2,
    SetActorData,
    SetActorMotion,
    SetActorLink,
    SetHealth,
    SetSpawnPosition,
    Animate,
    Respawn,
    ContainerOpen,
    ContainerClose,
    PlayerHotBar,
    InventoryContent,
    InventorySlot,
    ContainerSetData,
    CraftingData,
    CraftingEvent,
    GUIDataPickItem,
    AdventureSettings,
    BlockActorData,
    PlayerInput,
    LevelChunk,
    SetCommandsEnabled,
    SetDifficulty,
    ChangeDimension,
    SetPlayerGameType,
    PlayerList,
    SimpleEvent,
    Event,
    SpawnExperienceOrb,
    ClientBoundMapItemData,
    MapInfoRequest,
    RequestChunkRadius,
    ChunkRadiusUpdated,
    ItemFrameDropItem,
    GameRulesChanged,
    Camera,
    BossEvent,
    ShowCredits,
    AvailableCommands,
    CommandRequest,
    CommandBlockUpdate,
    CommandOutput,
    UpdateTrade,
    UpdateEquip,
    ResourcePackDataInfo,
    ResourcePackChunkData,
    ResourcePackChunkRequest,
    Transfer,
    PlaySound,
    StopSound,
    SetTitle,
    AddBehaviourTree,
    StructureBlockUpdate,
    ShowStoreOffer,
    PurchaseReceipt,
    PlayerSkin,
    SubClientLogin,
    AutomationClientConnect,
    SetLastHurtBy,
    BookEdit,
    NPCRequest,
    PhotoTransfer,
    ModalFormRequest,
    ModalFormResponse,
    ServerSettingsRequest,
    ServerSettingsResponse,
    ShowProfile,
    SetDefaultGameType,
    RemoveObjective,
    SetDisplayObjective,
    SetScore,
    LabTable,
    UpdateBlockSynced,
    MoveActorDelta,
    SetScoreboardIdentity,
    SetLocalPlayerAsInitialised,
    UpdateSoftEnum,
    NetworkStackLatency,

    // Skip 1

    ScriptCustomEvent = NetworkStackLatency + 2,
    SpawnParticleEffect,
    AvailableActorIdentifiers,

    // Skip 1

    NetworkChunkPublisherUpdate = AvailableActorIdentifiers + 2,
    BiomeDefinitionList,
    LevelSoundEvent,
    LevelEventGeneric,
    LecternUpdate,

    // Skip 1

    AddEntity = LecternUpdate + 2,
    RemoveEntity,
    ClientCacheStatus,
    MapCreateLockedCopy,
    OnScreenTextureAnimation,
    StructureTemplateDataRequest,
    StructureTemplateDataResponse,

    // Skip 1

    ClientCacheBlobStatus = StructureTemplateDataResponse + 2,
    ClientCacheMissResponse,
    EducationSettings,
    Emote,
    MultiPlayerSettings,
    SettingsCommand,
    AnvilDamage,
    CompletedUsingItem,
    NetworkSettings,
    PlayerAuthInput,
    CreativeContent,
    PlayerEnchantOptions,
    ItemStackRequest,
    ItemStackResponse,
    PlayerArmourDamage,
    CodeBuilder,
    UpdatePlayerGameType,
    EmoteList,
    PositionTrackingDBServerBroadcast,
    PositionTrackingDBClientRequest,
    DebugInfo,
    PacketViolationWarning,
    MotionPredictionHints,
    AnimateEntity,
    CameraShake,
    PlayerFog,
    CorrectPlayerMovePrediction,
    ItemComponent,
    FilterText,
    ClientBoundDebugRenderer,
    SyncActorProperty,
    AddVolumeEntity,
    RemoveVolumeEntity,
    SimulationType,
    NPCDialogue,
    EducationResourceURI,
    CreatePhoto,
    UpdateSubChunkBlocks,
    PhotoInfoRequest,
    SubChunk,
    SubChunkRequest,
    ClientStartItemCooldown,
    ScriptMessage,
    CodeBuilderSource,
};
}
}  // namespace Protocol
}  // namespace ProtoRock